# List vs Array

In [50]:
import numpy as np

In [44]:
L = [1, 2, 3]

In [45]:
A = np.array([1, 2, 3])

In [46]:
for e in L:
  print(e)

1
2
3


In [47]:
for e in A:
  print(e)

1
2
3


In [48]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [49]:
A.append(4)

AttributeError: ignored

In [ ]:
L + [5]

In [ ]:
A + np.array([4])

In [ ]:
A + np.array([4, 5, 6])

In [ ]:
A + np.array([4, 5])

In [ ]:
2 * A

In [ ]:
2 * L

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)
print(L2)

In [ ]:
L2 = [e+3 for e in L]
L2

In [ ]:
A **2

In [ ]:
np.sqrt(A)


In [ ]:
np.log(A)


In [ ]:
np.exp(A)

In [ ]:
np.tanh(A)

# Dot Product

In [ ]:
a = np.array([1, 2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a*b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

In [ ]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Matrics

In [1]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [2]:
L[0]

[1, 2]

In [3]:
L[0][1]

2

In [9]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [11]:
A[0][1]

2

In [12]:
A[0,1]

2

In [14]:
A[:,0]

array([1, 3])

In [15]:
A.T

array([[1, 3],
       [2, 4]])

In [16]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [17]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [19]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [23]:
A.dot(B.T)

ValueError: ignored

In [26]:
np.linalg.det(A)

-2.0000000000000004

In [28]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [31]:
np.trace(A)

5

In [33]:
np.diag(A)

array([1, 4])

In [34]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [35]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [36]:
Lam, V = np.linalg.eig(A)

In [37]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [38]:
V[:,0] * Lam[0] , A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [39]:
np.allclose(V[:,0] * Lam[0] , A @ V[:,0])

True

In [40]:
np.allclose(V @ np.diag(Lam), A @ V)

True

#  Solving Linear Systems

In [4]:
A = np.array([[1,1], [1.5,4]])
b = np.array([2200, 5050])

In [5]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [6]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Generate Data

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
11* np.ones((2,3))

array([[11., 11., 11.],
       [11., 11., 11.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.random()

0.1858554456751097

In [16]:
np.random.random((2,3))

array([[0.01297846, 0.65801456, 0.99540664],
       [0.32449292, 0.61017287, 0.00906953]])

In [18]:
np.random.randn(2,3) #doesnt take a tuple

array([[-0.36686019, -0.14900039, -0.33978433],
       [ 1.11020603, -0.91334671,  0.47609649]])

In [19]:
R= np.random.randn(1000)

In [21]:
R.mean()

0.01643419088869802

In [23]:
np.mean(R)

0.01643419088869802

In [25]:
R.var()

1.0160561014110452

In [27]:
R.std()

1.0079960820415153

In [28]:
R = np.random.randn(10000, 3)

In [31]:
R.mean(axis=0) #finds the mean of each column

array([ 0.02281866,  0.00084171, -0.01389902])

In [33]:
R.mean(axis=1) #finds the mean of each row

array([ 0.28361773, -0.40644324, -0.03334084, ..., -0.18497409,
       -0.18726197, -0.51940628])

In [35]:
R.mean(axis=1).shape

(10000,)

In [37]:
np.cov(R).shape

(10000, 10000)

In [39]:
np.cov(R.T)

array([[ 1.00928464,  0.00630091, -0.00663912],
       [ 0.00630091,  0.99907653,  0.00611869],
       [-0.00663912,  0.00611869,  0.99194364]])

In [40]:
np.cov(R, rowvar=False)

array([[ 1.00928464,  0.00630091, -0.00663912],
       [ 0.00630091,  0.99907653,  0.00611869],
       [-0.00663912,  0.00611869,  0.99194364]])

In [51]:
np.random.randint(0, 10, size=(3, 3))

array([[7, 5, 1],
       [4, 3, 2],
       [9, 2, 6]])

In [52]:
np.random.choice(10, size=(3,3))

array([[3, 4, 0],
       [6, 7, 4],
       [7, 9, 6]])

# Numpy Exercise

### Time Comparison

In [55]:
import numpy as np
from datetime import datetime

a = np.random.random((5,10))
b = np.random.random((10,5))
a_list = a.tolist()
b_list = b.T.tolist()
T = 100

solution_list = []

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a,b):
    result += e*f
  return result

def slow_matrix_mult(A,B):
  for row_index in range(len(A)):
    solution_row = []
    for column_index in range(len(B)):
      solution_row.append(slow_dot_product(A[row_index],B[column_index]))
  solution_list.append(solution_row)

t0 = datetime.now()
for t in range(T):
  numpy_solution = np.matmul(a,b)
dt1 = datetime.now() - t0
print('numpy solution in ', dt1.total_seconds(), 'seconds')

t0 = datetime.now()
for t in range(T):
  slow_matrix_mult(a_list,b_list)
dt2 = datetime.now() - t0
print('list solution in ', dt2.total_seconds(), 'seconds')

if(dt2.total_seconds() > dt1.total_seconds()):
  print('Numpy multiplication is', dt2.total_seconds()/dt1.total_seconds(), 'times faster than list multiplication')
else:
  print('List multiplication is', dt1.total_seconds()/dt2.total_seconds(), 'times faster than Numpy multiplication')

numpy solution in  0.000471 seconds
list solution in  0.005624 seconds
Numpy multiplication is 11.940552016985137 times faster than list multiplication
